<a href="https://colab.research.google.com/github/AmrElmowafy1977/AmrElmowafy1977/blob/main/Facebooh_ads.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

##Data Importing & Inspecting

In [3]:
df = pd.read_csv('/content/facebook_ads.csv', encoding = 'cp850')
df

Names                                             emails  \
0      Martina Avila  cubilia.Curae.Phasellus@quisaccumsanconvallis.edu   
1      Harlan Barnes                                eu.dolor@diam.co.uk   
2    Naomi Rodriquez  vulputate.mauris.sagittis@ametconsectetueradip...   
3    Jade Cunningham                            malesuada@dignissim.com   
4       Cedric Leach     felis.ullamcorper.viverra@egetmollislectus.net   
..               ...                                                ...   
494            Rigel            egestas.blandit.Nam@semvitaealiquam.com   
495           Walter                                ligula@Cumsociis.ca   
496            Vanna                 Cum.sociis.natoque@Sedmolestie.edu   
497            Pearl                      penatibus.et@massanonante.com   
498             Nell                  Quisque.varius@arcuVivamussit.net   

                   Country  Time Spent on Site       Salary  Clicked  
0                 Bulgaria           25.649648  55330.06006        0  
1                   Belize           32.456107  79049.07674        1  
2                  Algeria           20.945978  41098.60826        0  
3             Cook Islands           54.039325  37143.35536        1  
4                   Brazil           34.249729  37355.11276        0  
..                     ...                 ...          ...      ...  
494  Sao Tome and Principe           19.222746  44969.13495        0  
495                  Nepal           22.665662  41686.20425        0  
496               Zimbabwe           35.320239  23989.80864        0  
497            Philippines           26.539170  31708.57054        0  
498               Botswana           32.386148  74331.35442        1  

[499 rows x 6 columns]

In [4]:
df = df.drop(['Names','emails'],axis=1)
df

Country  Time Spent on Site       Salary  Clicked
0                 Bulgaria           25.649648  55330.06006        0
1                   Belize           32.456107  79049.07674        1
2                  Algeria           20.945978  41098.60826        0
3             Cook Islands           54.039325  37143.35536        1
4                   Brazil           34.249729  37355.11276        0
..                     ...                 ...          ...      ...
494  Sao Tome and Principe           19.222746  44969.13495        0
495                  Nepal           22.665662  41686.20425        0
496               Zimbabwe           35.320239  23989.80864        0
497            Philippines           26.539170  31708.57054        0
498               Botswana           32.386148  74331.35442        1

[499 rows x 4 columns]

##Data Preprocessing

In [16]:
X = df.iloc[:, : -1].values
X

array([['Bulgaria', 25.64964796, 55330.06006],
       ['Belize', 32.4561067, 79049.07674],
       ['Algeria', 20.9459779, 41098.60826],
       ...,
       ['Zimbabwe', 35.32023874, 23989.80864],
       ['Philippines', 26.53917023, 31708.57054],
       ['Botswana', 32.38614783, 74331.35442]], dtype=object)

In [17]:
y = df['Clicked'].values
y

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,

###Encoding Data

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
X[:,0] = le.fit_transform(X[:,0])
X[:,0] 

array([27, 17, 1, 41, 26, 100, 179, 45, 8, 171, 167, 66, 131, 140, 195,
       60, 185, 146, 34, 83, 176, 4, 133, 106, 105, 137, 39, 126, 46, 48,
       42, 24, 156, 56, 162, 28, 177, 189, 53, 57, 189, 20, 62, 124, 127,
       183, 47, 7, 180, 209, 191, 158, 200, 121, 175, 73, 50, 169, 18, 31,
       142, 97, 80, 80, 202, 112, 63, 96, 115, 61, 140, 149, 90, 168, 93,
       198, 147, 72, 69, 36, 165, 167, 49, 5, 91, 89, 49, 104, 82, 177,
       139, 64, 29, 125, 162, 33, 21, 97, 50, 69, 126, 124, 20, 192, 148,
       201, 184, 128, 161, 159, 154, 200, 195, 170, 3, 54, 128, 88, 85,
       37, 105, 101, 116, 49, 18, 101, 100, 153, 97, 83, 169, 109, 148,
       72, 9, 99, 120, 54, 113, 68, 159, 93, 52, 172, 205, 188, 138, 13,
       105, 47, 21, 163, 183, 143, 11, 140, 102, 44, 47, 208, 113, 115,
       193, 92, 104, 89, 95, 72, 65, 25, 182, 12, 98, 78, 58, 165, 209,
       207, 76, 203, 166, 1, 20, 205, 38, 155, 21, 136, 43, 90, 111, 114,
       74, 97, 75, 38, 106, 55, 96, 151, 85, 193, 

In [20]:
X

array([[27, 25.64964796, 55330.06006],
       [17, 32.4561067, 79049.07674],
       [1, 20.9459779, 41098.60826],
       ...,
       [208, 35.32023874, 23989.80864],
       [144, 26.53917023, 31708.57054],
       [24, 32.38614783, 74331.35442]], dtype=object)

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X= sc.fit_transform(X)

In [22]:
X

array([[-1.25375881, -0.79945766,  0.12825771],
       [-1.41990117, -0.05102869,  1.37859159],
       [-1.68572893, -1.31666684, -0.62194482],
       ...,
       [ 1.75341779,  0.26390739, -1.52382503],
       [ 0.69010673, -0.701647  , -1.11693508],
       [-1.30360152, -0.05872127,  1.12989966]])

###Splitting Data

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

##Model Building

In [24]:
import tensorflow.keras

In [26]:
from keras.models import Sequential
from keras.layers import Dense,ReLU

In [27]:
ann = Sequential()
ann.add(Dense(units=10, activation='ReLU'))
ann.add(Dense(units=10, activation='ReLU'))
ann.add(Dense(units=1, activation='sigmoid'))

In [28]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

##Model Training

In [29]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
13/13 [==============================] - 1s 3ms/step - loss: 0.6944 - accuracy: 0.6140
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6747 - accuracy: 0.7368
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6567 - accuracy: 0.7945
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6380 - accuracy: 0.8496
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 0.6172 - accuracy: 0.8722
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5943 - accuracy: 0.8922
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 0.5690 - accuracy: 0.8972
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5404 - accuracy: 0.9048
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5090 - accuracy: 0.9123
Epoch 10/100
13/13 [==============================] - 0s 2ms/step - loss: 0.4741 - accuracy: 0.9123
Epoch 11/

##Model Prediction

In [30]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


##Model Evaluation 


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[41  7]
 [ 8 44]]


0.85